### ISSUE TITLE
水淹分析绘制后报错

### ISSUE THREAD

**Issue by fuzhenn** [fuzhenn/examples.maptalks.com#64]
![image](https://user-images.githubusercontent.com/13678919/178896784-b3e57aed-3f53-4ea7-96dd-b65af1de0123.png)

**Comment by liubgithub** [comment]
3dtiles的identifyAtPoint方法返回的不是数组形式，导致groupgllayer在identify 3dtileslayer的时候拿不到坐标。
![image](https://user-images.githubusercontent.com/5208386/179016468-25bc788c-1213-45e6-b6a1-211a50dde5d7.png)
